services:
  frontend:
    build: 
      context: ./leaveManagement_FE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build: 
      context: ./LeaveManagementSystem
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lms4
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123123

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: