version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lms4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./LeaveManagementSystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Backend runs on 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lms4
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123123
    depends_on:
      - db

  frontend:
    build:
      context: ./leaveManagement_FE
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Map frontend container's 80 to host's 8081
    depends_on:
      - backend

volumes:
  pgdata: